# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=150)),
                ('notification_message', models.CharField(max_length=600)),
                ('notification_time', models.CharField(max_length=600)),
                ('notification_date', models.CharField(max_length=600)),
                ('notification_image', models.ImageField(blank=True, upload_to='notification_image/')),
                ('notification_event_id', models.IntegerField(blank=True, default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
