# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userdata_email'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated', models.IntegerField(blank=True, default=0, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventdata',
            name='type',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='image',
            field=models.ImageField(default='/media/event/default.png', upload_to='event/'),
        ),
        migrations.AddField(
            model_name='usereventdata',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventData'),
        ),
        migrations.AddField(
            model_name='usereventdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.UserData'),
        ),
    ]
