# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180116_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='image_blur',
            field=models.ImageField(default='/media/event/default.png', upload_to='event/'),
        ),
    ]
