# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventdata_image_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
