# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventdata_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='prize_description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
