# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventdata_prize_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='image_landscape',
            field=models.ImageField(default='/media/event/default.png', upload_to='event/'),
        ),
    ]
