# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180121_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='rules',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
