# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fcm', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
