# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
